### PR TITLE
Transform A/B Street JSON scenario files into the new format, as a

### PR DESCRIPTION
**Pull request by dabreegster**
workaround for https://github.com/a-b-street/abstr/issues/29.

I just ran a little Python script to modify all the files in-place:

```
#!/usr/bin/python3
# ./fix_json.py data-small/*/scenario_*.json

import json
import sys

for path in sys.argv[1:]:
    with open(path) as f:
        data = json.load(f)
        for person in data['people']:
            origin = person['origin']
            del person['origin']
            assert(len(person['trips']) == 1)
            person['trips'][0]['origin'] = origin

        with open(path, 'w') as f:
            f.write(json.dumps(data, indent=2))
            f.close()
```

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great to see these changes, thanks! I think it will be better if we fix it further upstream in the build script with the updated version of `abstr`. Suggestion:

- [ ] Take a look at https://github.com/a-b-street/abstr/issues/29
- [ ] Try re-running the build process on a single development
- [ ] If that works and generates the same results do that for all
- [ ] If it's taking too long merge this PR and save that for another day

Sound like a plan?

**Comment by dabreegster** [comment]
I agree fixing upstream is the ideal fix. I have no resources to put into that, and in the meantime all of the actdev scenarios are broken, so this is the quick fix. No rush to merge the PR; I already fixed up the data on my side in https://github.com/a-b-street/abstreet/commit/ed59a8a386dcc5f4ec07c78283a42add208744b2 by pointing at this copy.

**Comment by Robinlovelace** [comment]
Thanks @dabreegster will aim to look at it later today. Loving the use of branches to fix things on the deployed app.

**Review by Robinlovelace — APPROVED** [review]
Great fix to support the new A/B Street schema so definite improvement. Will aim to get the upstream fix working, this will be a good standard to work to.

**Pull request merged**
